AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Z-Score Protype V1 Cloud Infrastructure Repo

Mappings:
  DBEndpointURLMap:
    localhost: 
      local: "http://host.docker.internal:8000"
      dev: "http://host.docker.internal:8000"
      prod: "http://host.docker.internal:8000"
    us-east-1:
      local: "http://host.docker.internal:8000"
      dev: "https://dynamodb.us-east-1.amazonaws.com"
      prod: "https://dynamodb.us-east-1.amazonaws.com"
  DBTableName:
    localhost:
      local: "DevTable"
      dev: "DevTable"
      prod: "DevTable"
    us-east-1:
      local: "DevTable"
      dev: "GamesTable"
      prod: "GamesTable"



Parameters:
  ENV:
    Description: Environment to run application
    Default: local
    Type: String
    AllowedValues:
      - local
      - dev
      - prod

Resources: 

  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GamesTable
      BillingMode: PAY_PER_REQUEST 
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: S
        - AttributeName: "snapshot"
          AttributeType: S
      KeySchema:
        - AttributeName: "gameId"
          KeyType: HASH
        - AttributeName: "snapshot"
          KeyType: RANGE

  DBInterfaceApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DBInterfaceApiFunction
      CodeUri: .
      Handler: functions/api/src/app.lambda_handler
      Timeout: 15
      Runtime: python3.9
      Tracing: Active
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: DBInterfaceApi
          DB_ENDPOINT_URL: !FindInMap [DBEndpointURLMap, !Ref "AWS::Region", !Ref ENV]
          DB_TABLE_NAME: !FindInMap [DBTableName, !Ref "AWS::Region", !Ref ENV]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /{path+}
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - dynamodb:GetItem
                - dynamodb:GetBatchItem
                - dynamodb:PutItem
                - dyanmodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:BatchWriteItem
                - dynamodb:Scan
              Resource:
                - !GetAtt GamesTable.Arn

      

